# MYSQL_INFO = "mysql_user:mysql_user@tcp(127.0.0.1:3306)/testDB"
APP_NAME: "server"
APP_PORT: "8080"

DB_DRIVER: "mysql"
DB_HOST: "localhost"
DB_PORT: 3306
DB_NAME: "testDB"
DB_USER: "mysql_user"
DB_PASSWORD: "mysql_user"
DB_MAX_POOL_SIZE: 5
DB_MAX_OPEN_CONS: 5
DB_MAX_LIFE_TIME_MINS: 30
MIGRATION_PATH: "./migrations"
